---
- name: Create directory for version check
  file:
    path: "{{ tsUserHome }}/ts-version-check"
    state: directory
    owner: "{{ tsUserName }}"
    group: "{{ tsUserName }}"
    mode: 0750

### continue here
- name: Copy version_check python
  copy:
    src: version_check/version-check.py
    dest: /home/teamspeak/version_check/version-check.py
    owner: teamspeak
    group: teamspeak
    mode: 0660

- name: Copy version_check config
  copy:
    src: version_check/config.ini
    dest: /home/teamspeak/version_check/config.ini
    owner: teamspeak
    group: teamspeak
    mode: 0660

- name: Create cronjob for version check
  cron:
    name: Check for latest TeamSpeak verion
    minute: 36
    hour: 4
    job: python /home/teamspeak/version_check/version_check.py
